### ISSUE TITLE
[error] It is not running as expected.

### ISSUE THREAD

**Issue by ac1982** [daodao97/chatdoc#1]
1.Is your Python version 3.8? You still need to add ```python-multipart``` to the ```requirements.txt file```.
2.Get an error with  ```can not find data directory```.
3.When I try to upload a file, nothing happens.

**Comment by daodao97** [comment]
Please pull this repo, and try again.  [new change commit](https://github.com/daodao97/chatdoc/commit/5b1f1f1fb02d98ac4321c90016c9bd5d5c671560)

> My Local Env: Python 3.9.7  Node.js v16.11.0

**Comment by ac1982** [comment]
Nothing happen when browsering

server was stop at
```
INFO:llama_index.token_counter.token_counter:> [build_index_from_documents] Total LLM token usage: 0 tokens
> [build_index_from_documents] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [build_index_from_documents] Total embedding token usage: 4560 tokens
> [build_index_from_documents] Total embedding token usage: 4560 tokens
```

**Comment by daodao97** [comment]
这个是索引已经构建成功了
