### ISSUE TITLE
中间部分不显示文章内容。

### ISSUE THREAD

**Issue by unlceli** [daodao97/chatdoc#12]
![截屏2023-03-31 09 59 42](https://user-images.githubusercontent.com/15527719/229005710-d1bdd9db-10bf-4b51-b09d-9f958458a904.png)

您好，前端和后端的项目已经跑通，上传文件左侧显示内容，中间不显示详情。 后台无任何报错信息。 请问什么问题？

**Comment by unlceli** [comment]
补充：
<img width="1225" alt="WeChat7616bf292f8d595096796039d1cc065d" src="https://user-images.githubusercontent.com/15527719/229006585-82027ed3-069c-4122-a010-56121bb4c517.png">
点击该按钮，能看到文件是正常显示的。

**Comment by unlceli** [comment]
https://github.com/daodao97/chatdoc/blob/master/server/main.py#L13

**Comment by 1245244103** [comment]
> 补充： <img alt="WeChat7616bf292f8d595096796039d1cc065d" width="1225" src="https://user-images.githubusercontent.com/15527719/229006585-82027ed3-069c-4122-a010-56121bb4c517.png"> 点击该按钮，能看到文件是正常显示的。
你好，我也遇到了这个问题，请问你解决了吗
