### ISSUE TITLE
你好daodao97，我有个问题向您请教，谢谢。

### ISSUE THREAD

**Issue by sherry0630** [daodao97/chatdoc#14]
我 运行 docker-compose up 后 会报这个错：
chatdoc-backend   | Traceback (most recent call last):
chatdoc-backend   |   File "/data/main.py", line 104, in <module>
chatdoc-backend   |     uvicorn.run('main:app', host="0.0.0.0", reload=True)
chatdoc-backend   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 563, in run
chatdoc-backend   |     ChangeReload(config, target=server.run, sockets=[sock]).run()
chatdoc-backend   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/supervisors/basereload.py", line 45, in run
chatdoc-backend   |     for changes in self:
chatdoc-backend   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/supervisors/basereload.py", line 64, in __next__
chatdoc-backend   |     return self.should_restart()
chatdoc-backend   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/supervisors/statreload.py", line 32, in should_restart
chatdoc-backend   |     for file in self.iter_py_files():
chatdoc-backend   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/supervisors/statreload.py", line 52, in iter_py_files
chatdoc-backend   |     for path in list(reload_dir.rglob("*.py")):
chatdoc-backend   |   File "/usr/local/lib/python3.9/pathlib.py", line 1190, in rglob
chatdoc-backend   |     for p in selector.select_from(self):
chatdoc-backend   |   File "/usr/local/lib/python3.9/pathlib.py", line 611, in _select_from
chatdoc-backend   |     for p in successor_select(starting_point, is_dir, exists, scandir):
chatdoc-backend   |   File "/usr/local/lib/python3.9/pathlib.py", line 558, in _select_from
chatdoc-backend   |     with scandir(parent_path) as scandir_it:
chatdoc-backend   | FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/VMBUS:00/383305f1-d159-11ed-85a4-8038fb684b70'
 但是在docker desktop 中看两个容器都没挂 不过http://localhost:5173/打不开。我是四处搜索也没找到原因，只好请教您了。

**Comment by daodao97** [comment]
这个日志看不出什么嘞，得再多点新意

**Comment by sherry0630** [comment]
> 谢谢DAODAO，之前的报错解决了
现在出现新问题：
chatdoc-backend   | Successfully built EbookLib llama_index docx2txt python-multipart
chatdoc-backend   | Installing collected packages: rfc3986, pytz, logzero, docx2txt, urllib3, typing-extensions, tqdm, tenacity, soupsieve, sniffio, six, regex, PyYAML, packaging, numpy, mypy-extensions, multidict, lxml, idna, h11, greenlet, frozenlist, click, charset-normalizer, certifi, attrs, async-timeout, yarl, uvicorn, typing-inspect, SQLAlchemy, requests, python-multipart, python-dateutil, PyPDF2, pydantic, marshmallow, httpcore, EbookLib, beautifulsoup4, anyio, aiosignal, absl-py, tiktoken, starlette, pandas, marshmallow-enum, httpx, aiohttp, openai, fastapi, epub2txt, dataclasses-json, langchain, llama_index
chatdoc-frontend  | 3:33:12 PM [vite] http proxy error at /my_docs:
chatdoc-frontend  | Error: connect ECONNREFUSED 127.0.0.1:8000
chatdoc-frontend  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1532:16)
而且打不开公众号了

**Comment by daodao97** [comment]
看着是后端服务没正常启动，所以无法上传
