### ISSUE TITLE
sqlite3.OperationalError: no such table: docs

### ISSUE THREAD

**Issue by RipperTs** [daodao97/chatdoc#23]

**Comment by RipperTs** [comment]
好像没有初始化数据库的脚本呢

**Comment by daodao97** [comment]
哦, 刚发现 db 的初始文件被早上的一个 [pr](https://github.com/daodao97/chatdoc/pull/20/files#diff-1e2c0779a68abb3e363bf6b9b92182c30879a754903e9dabee4f355f18daf31f) 给删除了,
可以 运行下 `db_init.py`, 会重建
