### ISSUE TITLE
http://localhost:5173/界面连接不上

### ISSUE THREAD

**Issue by puppyjuan** [daodao97/chatdoc#28]
请问daodao老师，我这样运行了后，在http://localhost:5173/界面连接不上。我的操作过程怎么不对呢？
![微信图片_20230420112448](https://user-images.githubusercontent.com/57520204/233250514-8353e59c-fff7-40aa-9b0f-03eb5422f195.png)

**Comment by daodao97** [comment]
看着前后端服务并未启动嘞，正常应该有日志输出的
