### ISSUE TITLE
请问OPEN_AI_KEY怎么获取

### ISSUE THREAD

**Issue by lonelysheeep** [daodao97/chatdoc#33]
请问OPEN_AI_KEY怎么获取

**Comment by melody4482** [comment]
You can get the OpenAI API KEY in [OpenAI API KEY](https://platform.openai.com/account/api-keys) website.
You should login to the openai website and then, you can create your openai api key.
If you wanna use gpt-4, you must pay for that.
GPT-3.5 is free version
