### ISSUE TITLE
Select, Click feature

### ISSUE THREAD

**Issue by hieudx149** [daodao97/chatdoc#43]
Hi @daodao97, Your work is awesome. I've tried using another tool called [ChatDoc](https://chatdoc.com/), which is quite similar to your work. This tool has a select, click, and ask feature that allows users to select a segment in a PDF or DOC file and display it on the right side. I would like to implement this feature in my own tool, but I'm not sure how to do it. Could you please provide me with some advice or guidelines to help me? Thank you!

**Comment by daodao97** [comment]
I cannot provide an exact answer to this question, but you can explore other people's implementations. There are plenty of source code examples available on GitHub that we can learn from, such as https://github.com/openai/openai-cookbook. By studying these examples, we can gain a lot of ideas and inspiration.
